title: JCP HEP School
description: JCP HEP School
lang: en
baseurl: /JCP
url: https://HEPschool.github.io
markdown: kramdown
timezone: Asia/Seoul
plugins:
- jekyll-seo-tag
#- jekyll-sitemap
kramdown:
  input: GFM
  hard_wrap: false
future: true
nav:
- name: Home
  url: /
- name: Schedule
  url: /schedule/
- name: Lecturers
  url: /lecturers/
- name: Materials
  url: /materials/
- name: Online Meeting
  url: /online/
collections:
  events:
    output: true
    permalink: /events/:slug/
  online:
    output: true
    permalink: /online/:slug/
nav_next_label: Upcoming Event
